
server:
  port: 8083
  
endpoints:
  sensitive: true
  health:
    sensitive: true

management:
  security:
    enabled: false

spring:
  boot:
    admin:
      url: http://monitor:8081
  application:
    name: Invoice
    
